# -*- coding: utf-8 -*-
{
    'name': "Barcode India",

    'summary': """
        """,

    'description': """
        
    """,

    'author': "Squad Softech",
    'website': "squadsoftech.com",

    # Categories can be used to filter modules in modules listing
    # Check https://github.com/odoo/odoo/blob/15.0/odoo/addons/base/data/ir_module_category_data.xml
    # for the full list
    'category': 'Uncategorized',
    'version': '0.1',

    # any module necessary for this one to work correctly
    'depends': ['base', 'web','sale_management', 'sale','contacts','product','stock','helpdesk','helpdesk_fsm','project','survey','mass_mailing','sale_crm','base_automation','cost_estimation','approvals','purchase','worksheet','l10n_in','asc_mail','sales_team','mail', 'delivery'],

    # always loaded
    'data': [
        'security/ir.model.access.csv',
        'security/Groups.xml',
        'data/Sequence.xml',
        'wizards/views/RMATransfer.xml',
        'views/ConfigurationSettings.xml',
        'views/Integrations.xml',
        'views/AccountSetCode.xml',
        'views/Partners.xml',
        'views/Products.xml',
        'views/RejectReason.xml',
        'views/ProductCategories.xml',
        'views/LeadStatus.xml',    
        'views/ContractDetails.xml',
        'views/Lob.xml',
        'views/Status.xml',
        'data/LeadStatus.xml',
        'views/CrmTeam.xml',
        'views/Users.xml',
        'views/ContractStage.xml',
        'views/ContractType.xml',
        'views/Sites.xml',
        'views/Contracts.xml',
        'views/ContractSync.xml',
        'views/AssetsStage.xml',
        'views/Assets.xml',
        'views/ResolutionType.xml',
        'views/ReasonCode.xml',
        'views/CaseType.xml',
        'views/CaseSubType.xml',
        'views/ProblemType.xml',
        'views/ProblemSubType.xml',
        'views/Chargeable.xml',
        'views/Sales.xml',
        'views/Helpdesk.xml',
        'views/Projects.xml',
        'views/Mailings.xml',
        'views/MailingContacts.xml',
        'views/RMAMaster.xml',
        'views/LeadType.xml',
        'views/Region.xml',
        'views/Vertical.xml',
        'views/SubVertical.xml',
        'views/SubVerticalCategory.xml',
        'views/GroupCode.xml',
        'views/TaxGroup.xml',
        'views/TermsCode.xml',
        'views/ApplicationType.xml',
        'views/Activities.xml',
        'views/Probability.xml',
        'views/Stages.xml',
        'views/ProjectTask.xml',
        'views/SaleOrderLine.xml',
        'views/PricingCategory.xml',
        'views/TermsConditions.xml',
        'views/Crm.xml',
        # 'views/PaymentTerms.xml',
        'views/PricingFactor.xml',
        'views/DiscountCategory.xml',
        'views/CostsheetViewMaster.xml',
        'views/QuotationType.xml',
        'views/SalePersonLimit.xml',
        'views/LocationWiseInventory.xml',
        'views/Approval.xml',
        # 'views/Paymentmatrix.xml',
        # 'views/Marginmatrix.xml',
        'views/TestCaseStatus.xml',
        'views/TestCases.xml',
        
        'views/StockPicking.xml',
        'views/Spare.xml',
        'views/PMStatus.xml',
        'views/StockLocation.xml',
        'views/ERPCategory.xml',
        'views/LineOfBusiness.xml',
        'views/SuperCategory.xml',
        'views/Coverage.xml',
        'views/CoverageType.xml',
        'views/OEM.xml',
        'views/OnsiteCoverage.xml',
        'views/OwnCompany.xml',
        'views/ServiceCategory.xml',
        'views/StandbyEquipment.xml',
        'views/WarrantyAmc.xml',
        'views/InstallationType.xml',
        'views/FreightType.xml',
        'views/Escalation.xml',
        'views/LegacyAsset.xml',
        'views/Bant.xml',
        'views/AssignReportMatrix.xml',
        'views/AccountTaxes.xml',
        'views/SopfHeader.xml',
        'views/SopfItems.xml',
        'views/ModelNumber.xml',
        'views/MenuItems.xml',
        'reports/SaleOrder.xml',
        # 'reports/Sopf_report.xml',
        # 'reports/Worksheet_template.xml',
        # 'reports/crm_report.xml',
        # 'reports/ProjectStatus.xml',
        # 'data/WorksheetFsm.xml',
        'wizards/views/UpdateSurvey.xml',
        'wizards/views/ApprovePaymentTerm.xml',
        'wizards/views/CreateQuotation.xml',
        'wizards/views/ChangeAsset.xml',
        'wizards/views/SaleLines.xml',
        'wizards/views/ApprovalFor.xml',
        'wizards/views/RejectReason.xml',
        'wizards/views/PreSales.xml',
        'wizards/views/RePricing.xml',
        'wizards/views/CreateSOPF.xml',
        'wizards/views/CRMLost.xml',
        'wizards/views/HelpdeskTicketHold.xml',
        'data/EmailNotificationAssets.xml',
        # 'data/AutomatedAction.xml',
        'data/ir_cron_data.xml',
        'data/Integration.xml',
        'data/ApprovalTemplates.xml',
        'data/ApprovalCategoryData.xml',
        'data/OpportunityTemplates.xml',
    ],
    # only loaded in demonstration mode
    'application':True,
}
